/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Helper.DBBooking;
import Helper.DBLapangan;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import Controller.LapanganController;

/**
 *
 * @author ASUS
 */
public class AdminView extends javax.swing.JFrame {
    int idLapangan = 0;
    LapanganController lc =
        new LapanganController();
    /**
     * Creates new form AdminView
     */
   public AdminView(String username) {

    initComponents();

    Admin.setText(
            "Halo, " + username
    );

    panelContent.add(panelLapangan, "lapangan");

    panelContent.add(panelBooking, "booking");

    loadTableLapangan();

    loadTableBooking();
}
    
    private void loadTableLapangan() {

        DefaultTableModel model =
                new DefaultTableModel();

        model.setRowCount(0);

        model.addColumn("ID");
        model.addColumn("Nama Lapangan");
        model.addColumn("Harga per Jam");
        model.addColumn("Status");

        try {

            ResultSet rs =
                    DBLapangan.getLapangan();

            while (rs.next()) {

                model.addRow(new Object[]{
                    rs.getInt("id_lapangan"),
                    rs.getString("nama_lapangan"),
                    rs.getInt("harga_per_jam"),
                    rs.getString("status")
                });

            }

            tableLapangan.setModel(model);
            
            // hide ID 
            tableLapangan.getColumnModel()
                    .getColumn(0)
                    .setMinWidth(0);

            tableLapangan.getColumnModel()
                    .getColumn(0)
                    .setMaxWidth(0);

            tableLapangan.getColumnModel()
                    .getColumn(0)
                    .setWidth(0);

        } catch (Exception e) {

            System.out.println(e);

        }

    }
    
    private void loadTableBooking() {

    DefaultTableModel model =
            new DefaultTableModel();

    model.addColumn("Nama Pemesan");
    model.addColumn("Lapangan");
    model.addColumn("Tanggal");
    model.addColumn("Jam");
    model.addColumn("Durasi");
    model.addColumn("Total");
    model.addColumn("Status");

    try {

        ResultSet rs =
                DBBooking.getBooking();

        while (rs.next()) {

            String jam =
                    rs.getString("jam_mulai")
                    + " - " +
                    rs.getString("jam_selesai");

            model.addRow(new Object[]{

                rs.getString("nama_pemesan"),

                rs.getString("nama_lapangan"),

                rs.getString("tanggal"),

                jam,

                rs.getInt("durasi") + " jam",

                "Rp " + rs.getInt("total_harga"),

                rs.getString("status")

            });

        }

        jTable2.setModel(model);

    } catch (Exception e) {

        System.out.println(e);

    }

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        panelSidebar = new javax.swing.JPanel();
        Admin = new javax.swing.JLabel();
        btnMenuLapangan = new javax.swing.JButton();
        btnMenuBooking = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        panelContent = new javax.swing.JPanel();
        panelLapangan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLapangan = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btnHapus = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        cbStatus = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        Harga = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        NamaLapangan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        panelBooking = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 500));

        panelSidebar.setBackground(new java.awt.Color(255, 255, 255));
        panelSidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Admin.setBackground(new java.awt.Color(255, 255, 255));
        Admin.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        Admin.setForeground(new java.awt.Color(255, 255, 255));
        Admin.setText("Halo, ADMIN");
        panelSidebar.add(Admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 110, 32));

        btnMenuLapangan.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnMenuLapangan.setText("Kelola Lapangan");
        btnMenuLapangan.setPreferredSize(new java.awt.Dimension(115, 23));
        btnMenuLapangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuLapanganActionPerformed(evt);
            }
        });
        panelSidebar.add(btnMenuLapangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 140, 30));

        btnMenuBooking.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnMenuBooking.setText("Data Booking");
        btnMenuBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuBookingActionPerformed(evt);
            }
        });
        panelSidebar.add(btnMenuBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 140, 30));

        btnLogout.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        panelSidebar.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 140, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/bg_login.png.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        panelSidebar.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 690));

        panelContent.setLayout(new java.awt.CardLayout());

        panelLapangan.setBackground(new java.awt.Color(255, 255, 255));
        panelLapangan.setMaximumSize(new java.awt.Dimension(900, 500));
        panelLapangan.setMinimumSize(new java.awt.Dimension(1280, 720));
        panelLapangan.setPreferredSize(new java.awt.Dimension(1100, 720));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setText("Kelola Lapangan");

        tableLapangan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tableLapangan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nama Lapangan", "Harga per Jam", "Status"
            }
        ));
        tableLapangan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableLapanganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableLapangan);

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel5.setText("Data Lapangan");

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHapus.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel7.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 100, 30));

        btnClear.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel7.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 100, 30));

        btnTambah.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        btnTambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTambah.setText("TAMBAH");
        btnTambah.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        jPanel7.add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 100, 30));

        btnEdit.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Yellow"));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEdit.setText("UPDATE");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel7.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 100, 30));

        cbStatus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tersedia", "maintenance" }));
        cbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbStatusActionPerformed(evt);
            }
        });
        jPanel7.add(cbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 250, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Status");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 70, 20));

        Harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HargaActionPerformed(evt);
            }
        });
        jPanel7.add(Harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 250, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Harga");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 70, 40));

        NamaLapangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaLapanganActionPerformed(evt);
            }
        });
        jPanel7.add(NamaLapangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 250, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Nama Lapangan");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        javax.swing.GroupLayout panelLapanganLayout = new javax.swing.GroupLayout(panelLapangan);
        panelLapangan.setLayout(panelLapanganLayout);
        panelLapanganLayout.setHorizontalGroup(
            panelLapanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLapanganLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(panelLapanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(panelLapanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(289, Short.MAX_VALUE))
        );
        panelLapanganLayout.setVerticalGroup(
            panelLapanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLapanganLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelLapanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(panelLapanganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(253, Short.MAX_VALUE))
        );

        panelContent.add(panelLapangan, "card3");

        panelBooking.setBackground(new java.awt.Color(255, 255, 255));
        panelBooking.setMaximumSize(new java.awt.Dimension(0, 0));
        panelBooking.setPreferredSize(new java.awt.Dimension(950, 500));
        panelBooking.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setPreferredSize(new java.awt.Dimension(950, 500));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nama User", "Lapangan", "Tanggal", "Jam", "Total (Rp)", "Status"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        panelBooking.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 60, 860, 352));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Daftar Data Booking");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelBooking.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 230, 28));

        panelContent.add(panelBooking, "booking");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelSidebar, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelSidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(406, Short.MAX_VALUE))
        );

        panelSidebar.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuLapanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuLapanganActionPerformed
        // TODO add your handling code here:
        java.awt.CardLayout cl =
            (java.awt.CardLayout)
                    panelContent.getLayout();

        cl.show(panelContent, "lapangan");
    }//GEN-LAST:event_btnMenuLapanganActionPerformed

    private void btnMenuBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuBookingActionPerformed
        // TODO add your handling code here:
        java.awt.CardLayout cl =
            (java.awt.CardLayout)
                    panelContent.getLayout();

        cl.show(panelContent, "booking");
    }//GEN-LAST:event_btnMenuBookingActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int konfirmasi =
        JOptionPane.showConfirmDialog(
                this,
                "Yakin ingin menghapus data ini?",
                "Konfirmasi Hapus",
                JOptionPane.YES_NO_OPTION
        );

if (konfirmasi == JOptionPane.YES_OPTION) {

    lc.hapusLapangan(
        idLapangan
);

    JOptionPane.showMessageDialog(
            this,
            "Data berhasil dihapus"
    );

    loadTableLapangan();
    

}

    }//GEN-LAST:event_btnHapusActionPerformed
    
    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
            String nama =
            NamaLapangan.getText();

    int harga =
            Integer.parseInt(
                    Harga.getText()
            );

    String status =
            cbStatus.getSelectedItem()
                    .toString();

    lc.editLapangan(
        idLapangan,
        nama,
        harga,
        status
);

    JOptionPane.showMessageDialog(
            this,
            "Data berhasil diupdate"
    );

loadTableLapangan();
        
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        System.out.println("BUTTON KLIK");
        String nama =
        NamaLapangan.getText();

        int harga =
            Integer.parseInt(
                    Harga.getText()
            );

        String status =
            cbStatus.getSelectedItem()
                    .toString();

        lc.tambahLapangan(
        nama,
        harga,
        status
);

        JOptionPane.showMessageDialog(
                this,
                "Data berhasil ditambah"
        );

        loadTableLapangan();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void NamaLapanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaLapanganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaLapanganActionPerformed

    private void cbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbStatusActionPerformed

    private void tableLapanganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableLapanganMouseClicked
        // TODO add your handling code here:
            int baris =
            tableLapangan.getSelectedRow();

    idLapangan =
            Integer.parseInt(
                    tableLapangan
                            .getValueAt(baris, 0)
                            .toString()
            );

    NamaLapangan.setText(
            tableLapangan
                    .getValueAt(baris, 1)
                    .toString()
    );

    Harga.setText(
            tableLapangan
                    .getValueAt(baris, 2)
                    .toString()
    );

    cbStatus.setSelectedItem(
            tableLapangan
                    .getValueAt(baris, 3)
                    .toString()
    );
    }//GEN-LAST:event_tableLapanganMouseClicked

    private void HargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HargaActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        int pilih =
        JOptionPane.showConfirmDialog(
            this,
            "Yakin ingin logout?",
            "Logout",
            JOptionPane.YES_NO_OPTION
        );

        if (pilih == JOptionPane.YES_OPTION) {

            new LoginAdminView().setVisible(true);

            this.dispose();
        }
    }//GEN-LAST:event_btnLogoutActionPerformed
    
    private void clearForm() {

        NamaLapangan.setText("");

        Harga.setText("");

        cbStatus.setSelectedIndex(0);

        idLapangan = 0;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminView("ADMIN").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Admin;
    private javax.swing.JTextField Harga;
    private javax.swing.JTextField NamaLapangan;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMenuBooking;
    private javax.swing.JButton btnMenuLapangan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel panelBooking;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelLapangan;
    private javax.swing.JPanel panelSidebar;
    private javax.swing.JTable tableLapangan;
    // End of variables declaration//GEN-END:variables
}
